env:
  es6: false
  browser: true
  commonjs: true
parserOptions:
  sourceType: module
extends:
  - 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  brace-style:
    - error
    - 1tbs
  camelcase:
    - error
  array-bracket-spacing:
    - error
  object-curly-spacing:
    - error
  key-spacing:
    - error
  no-trailing-spaces:
    - error
  comma-spacing:
    - error
  computed-property-spacing:
    - error
  keyword-spacing:
    - error
  space-infix-ops: error
  space-unary-ops: error
  no-multi-spaces: warn
  space-before-blocks: error
  arrow-spacing: error
  space-in-parens:
    - error
    - never